### ISSUE TITLE
KeyError: 'fg_pred' when running the "lacss/experiments/livecell/semisupervised.py"

### ISSUE THREAD

**Issue by lphilomena** [jiyuuchc/lacss#11]
Hi, Sorry to bother you again. I run the "lacss/experiments/livecell/semisupervised.py" on the livecell dataset and met the following error:

Exception has occurred: KeyError
'fg_pred'
  File "/home/lacss/experiments/livecell/semisupervised.py", line 181, in run_training
    trainer.do_training(
  File "/home/lacss/experiments/livecell/semisupervised.py", line 197, in <module>
    app()
KeyError: 'fg_pred'

I tried to debug the semisupervised.py by the strategy: type = Core, however the program still did'nt set into the break points 
 set in lacss_trainer.py. Could you please tell me how to fix the above error or how to debug it? Looking forward to your reply and thank you very much!

**Comment by jiyuuchc** [comment]
Hmm, I cannot reproduce this. How did you setup your environment? Are you using the head version from github?

**Comment by lphilomena** [comment]
> Hmm, I cannot reproduce this. How did you setup your environment? Are you using the head version from github?

Thanks! I download the head version, it works！ I have another question about the livecell dataset and semisupervised.py file. There is no "centroids" info in the livecell json file, while gt_locations=inputs["centroids"] exists in the semisupervised.py file. I understand the centroids could be calculated accroding to the gt masks, but i didn't see code in the semisupervised.py file to do this. Could you please tell me where did you do it?

**Comment by lphilomena** [comment]
> Hmm, I cannot reproduce this. How did you setup your environment? Are you using the head version from github?

Thanks! I download the head version and it works!

**Comment by jiyuuchc** [comment]
All data generators (and augmentation functions) are in the lacss.data package. Specifically for COCO annotation (which LIVECell uses), see coco_generator_full()  (https://jiyuuchc.github.io/lacss/api/data/#lacss.data.generator.coco_generator_full)

Ji

________________________________________

**Comment by jiyuuchc** [comment]
close as resolved.
