### ISSUE TITLE
Your code in google collab are not working expect Inference.py

### ISSUE THREAD

**Issue by codesmith25103** [jiyuuchc/lacss#12]
While running the Supervised Training.ipynb in google collab. I got error "TypeError: Lacss.__call__() got an unexpected keyword argument 'gt_locations'". 
![image](https://github.com/user-attachments/assets/c2508019-e163-411b-9502-a0af2f6694ff)

**Comment by codesmith25103** [comment]
While running "point with label only.ipynb". I am getting thise error 
![image](https://github.com/user-attachments/assets/7d25156b-3bc7-46ec-985a-daad2f4c5791)

**Comment by jiyuuchc** [comment]
Please use the `lacss1` branch for now.

If you are testing on CoLab, use the link: https://colab.research.google.com/github/jiyuuchc/lacss/blob/lacss1/notebooks/train_with_point_label.ipynb

The main branch has been undergoing a lot of updates (to support 3D segmentation, GRPC services etc) and we expect things to be somewhat broken for a while, until the release of 0.14

Ji

**Comment by lphilomena** [comment]
Hi，is the main branch working now? I met the same error when running "train_with_point_label.py".

**Comment by codesmith25103** [comment]
@jiyuuchc Thanks for CoLab link. It is working fine
