### ISSUE TITLE
Questions about training

### ISSUE THREAD

**Issue by pakiessling** [jiyuuchc/lacss#4]
Hi again.
With your very kind help in #3 I was able succesfully train lacss :) 
Starting from your tissuenet model. I trained on a hundred images with the parameters from With_point_label_only colab. As mask I just used a np.ones
https://github.com/pakiessling/lacss-test/blob/main/train_100_test.ipynb

I have some more (naive) questions about the training process.
1. What is the proper way of saving and restoring a saved model for prediction? from `lacss.deploy import pickle` and then` trainer.pickle("./100_test.pkl")`?
2. Can you give me some more info about `pi` and `sigma `in training? I assume `sigma` is the mean diameter of cells in pixels?
3. In the 18 000 epochs I trained, loss didnt really change much. Should I train for longer or is there something wrong? See below:
![grafik](https://github.com/jiyuuchc/lacss/assets/104848590/b89860b4-66de-400c-9fd7-35223bf84b7e)

Thank you!

**Comment by jiyuuchc** [comment]
The recommended way of saving training checkpoint is to specify a checkpoint manager in the do_training() call. See API document for example code of how to do this.

https://jiyuuchc.github.io/lacss/api/train/

You can load the checkpoint into lacss.deploy.Predictor class to perform model inference.

Another useful resource is the code in

experiments/livecell/semisupervised.py

which shows a more realistic training pipeline than the skeletal code in the demo notebook.

The livecell code also shows the proper way of model validation, by supplying a fully labeled validation dataset, assuming you have one. The validation metrics are better criteria for stopping than the loss values

The main loss function to monitor is lpn_loss, which should decrease as in normal supervised training. All other losses are regulatory losses and will not behave like a traditional loss.

The sigma and pi are both unitless. Sigma tried prior knowledge regarding cell sizes and pi is the confidence of this knowledge. The results are quite insensitive to the exact values of these, and for most use cases the default values should be ok. But users are free to perform their own hyperparameter scanning. For details, see

https://arxiv.org/abs/2304.10671


Ji
________________________________
From: pakiessling ***@***.***>
Sent: Friday, August 4, 2023 3:27:33 AM
To: jiyuuchc/lacss ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jiyuuchc/lacss] Questions about training (Issue #4)

*** Attention: This is an external email. Use caution responding, opening attachments or clicking on links. ***

Hi again.
With your very kind help in #3<https://urldefense.com/v3/__https://github.com/jiyuuchc/lacss/issues/3__;!!Cn_UX_p3!iQKjEXdtmCVfjfXJKpF6mH2YoCwDVbY1wY9G1q8owcQi24t2YPsnkiI9chxDnt_ScAXSF0GKR29fWM20uVJKiA$> I was able succesfully train lacss :)
Starting from your tissuenet model. I trained on a hundred images with the parameters from With_point_label_only colab. As mask I just used a np.ones
https://github.com/pakiessling/lacss-test/blob/main/train_100_test.ipynb<https://urldefense.com/v3/__https://github.com/pakiessling/lacss-test/blob/main/train_100_test.ipynb__;!!Cn_UX_p3!iQKjEXdtmCVfjfXJKpF6mH2YoCwDVbY1wY9G1q8owcQi24t2YPsnkiI9chxDnt_ScAXSF0GKR29fWM0nYq4e6w$>

I have some more questions about the training process.

  1.  What is the proper way of saving and restoring a saved model for prediction? from lacss.deploy import pickle and then trainer.pickle("./100_test.pkl")?
  2.  Can you give me some more info about pi and sigma in training? I assume sigma is the mean diameter of cells in pixels?
  3.  In the 18 000 epochs I trained, loss didnt really change much. Should I train for longer or is there something wrong? See below:
[grafik]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/104848590/258215814-b89860b4-66de-400c-9fd7-35223bf84b7e.png__;!!Cn_UX_p3!iQKjEXdtmCVfjfXJKpF6mH2YoCwDVbY1wY9G1q8owcQi24t2YPsnkiI9chxDnt_ScAXSF0GKR29fWM2TkC1t_g$>

Thank you!

**Comment by pakiessling** [comment]
Thanks for the in-depth answer Ji.
Can I use full annotations for annotation or do I need to "downgrade" them to bounding box and centroid?

**Comment by jiyuuchc** [comment]
No you don't need to downgrade the validataion dataset if it is already fully labeled.

The generator you want to use is probably this one:

https://jiyuuchc.github.io/lacss/api/data/#lacss.data.generator.dataset_from_img_mask_pairs

Make sure to apply the same normalization/scaling op if used on the training set.

Ji

________________________________________

**Comment by pakiessling** [comment]
Hi Ji,

sorry to bother you again.

I gave it a shot with the generator:
https://github.com/pakiessling/lacss-test/blob/main/lacss_validation_test.ipynb

Any idea what could cause the error: `INVALID_ARGUMENT: TypeError: generator yielded an element of shape (2048, 2048, 2) where an element of shape (None, None, 3) was expected.`?

**Comment by jiyuuchc** [comment]
Do this:

```
val1 =  (
    lacss.data.dataset_from_img_mask_pairs(
        val_images, 
        val_gt, 
        image_shape=[2048, 2048, 2],
    )
    .map(val_parser)
    .prefetch(10)
)
```

The default image_shape assume an RGB image.

**Comment by pakiessling** [comment]
That fixed it, thanks!

I am now running a test with only a single image for validation.
https://github.com/pakiessling/lacss-test/blob/main/train_100_with_validation.ipynb

Unfortunately, I get loi_ap: [0. 0. 0.] and box_ap: [0. 0.] at every validation.
I think the validation images are in the correct shape and size. Any ideas?

**Comment by jiyuuchc** [comment]
Could you post the full output from training? It would be helpful determining what went wrong.

One issue I can see is that there is a big mismatch of pixel size between your data and the original training data of the transfer model. I've previously suggested rescale your image. For train parse:

```
    # build-in data augmentation function
    data["image"] = tf.image.per_image_standardization(data["image"])
+   data["image"] = lacss.data.resize(data, target_size=[512,512]) # resize image to match pixel size
    data = lacss.data.random_resize(data, scaling=.2) # This is a random rescaling of 0.8-1.2
    data = lacss.data.random_crop_or_pad(data, target_size=[512,512])
```

Similarly for val_parse:

```
def val_parser(data):
    data["image"] = tf.image.per_image_standardization(data["image"])
    data["image"] = lacss.data.resize(data, target_size=[512,512]) # resize image to match pixel size

    locations = data['centroids']
    n_pad = 768 - len(locations)
    locations = tf.pad(locations, [[0, n_pad], [0,0]], constant_values=-1)

    return dict(image=tf.ensure_shape(data['image'], [512,512,2])),dict(gt_locations=data["centroids"],gt_bboxes=data["bboxes"])

```

I also removed random_resize op from the val_parse -- data augmentation is not needed for validation data.

**Comment by pakiessling** [comment]
Sure, full output here:
https://raw.githubusercontent.com/pakiessling/lacss-test/main/lacss_training_100.log

Thank you for your code example. I missunderstood how the resizing works. I will try once more.

For `data["image"] = lacss.data.resize(data, target_size=[512,512])` I receive a recursion error. Should it be  
`data = lacss.data.resize(data, target_size=[512,512])`?

**Comment by pakiessling** [comment]
Okay, resizing had an effect.
Loss at 2500 steps:
```
lpn_loss:0.0108, segmentation_loss:0.1961, collaborator_segm_loss:0.0373, collaborator_border_loss:0.0055, mc_loss:0.0385
loi_ap: [0.07169771 0.00132832 0.00010816]
box_ap: [0.0011614 0.       ]
```

Loss at 15000 steps:
```
lpn_loss:0.0051, segmentation_loss:0.2498, collaborator_segm_loss:0.0181, collaborator_border_loss:0.0052, mc_loss:0.0319
loi_ap: [0.08074705 0.00169231 0.00019474]
box_ap: [1.36806256e-03 1.73881786e-05]
```

That still seems very low right?

The training crashed shortly afterward:

<details>
  <summary>Log</summary>

```
259/2500 [04:34<03:15,  6.34it/s]<tifffile.TiffFile 'dummy'> asarray failed to reshape (0,) to ()
2023-08-11 12:19:29.954514: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: TypeError: `generator` yielded an element of shape (0,) where an element of shape (2048, 2048) was expected.
Traceback (most recent call last):

  File "/work/rwth1209/enviroments/lacss/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py", line 267, in __call__
    ret = func(*args)

  File "/work/rwth1209/enviroments/lacss/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "/work/rwth1209/enviroments/lacss/lib/python3.10/site-packages/tensorflow/python/data/ops/from_generator_op.py", line 235, in generator_py_func
    raise TypeError(

TypeError: `generator` yielded an element of shape (0,) where an element of shape (2048, 2048) was expected.



 50%|█████     | 1260/2500 [04:34<03:17,  6.26it/s]
 50%|█████     | 1261/2500 [04:34<03:18,  6.25it/s]
 50%|█████     | 1262/2500 [04:34<03:15,  6.32it/s]
 51%|█████     | 1263/2500 [04:34<03:15,  6.34it/s]
 51%|█████     | 1264/2500 [04:35<03:14,  6.37it/s]
 51%|█████     | 1265/2500 [04:35<03:13,  6.37it/s]
 51%|█████     | 1266/2500 [04:35<03:16,  6.30it/s]
 51%|█████     | 1267/2500 [04:35<03:13,  6.37it/s]
 51%|█████     | 1268/2500 [04:35<03:14,  6.32it/s]
 51%|█████     | 1268/2500 [04:35<04:27,  4.60it/s]
Traceback (most recent call last):
  File "/rwthfs/rz/cluster/work/rwth1209/projects/merfish_segmentation/scripts/lacss/train100_checkpoints_val.py", line 151, in <module>
    trainer.do_training(
  File "/work/rwth1209/enviroments/lacss/lib/python3.10/site-packages/lacss/train/lacss_trainer.py", line 318, in do_training
    logs = next(train_iter)
  File "/work/rwth1209/enviroments/lacss/lib/python3.10/site-packages/lacss/train/trainer.py", line 231, in train
    for step, data in enumerate(_get_iterator(dataset)):
  File "/work/rwth1209/enviroments/lacss/lib/python3.10/site-packages/lacss/train/data/tf_dataset_adapter.py", line 38, in parse_tf_data_gen
    for batch in iter(self._dataset):
  File "/work/rwth1209/enviroments/lacss/lib/python3.10/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 797, in __next__
    return self._next_internal()
  File "/work/rwth1209/enviroments/lacss/lib/python3.10/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 780, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
  File "/work/rwth1209/enviroments/lacss/lib/python3.10/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 3016, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/work/rwth1209/enviroments/lacss/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 7262, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} TypeError: `generator` yielded an element of shape (0,) where an element of shape (2048, 2048) was expected.
Traceback (most recent call last):

  File "/work/rwth1209/enviroments/lacss/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py", line 267, in __call__
    ret = func(*args)

  File "/work/rwth1209/enviroments/lacss/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "/work/rwth1209/enviroments/lacss/lib/python3.10/site-packages/tensorflow/python/data/ops/from_generator_op.py", line 235, in generator_py_func
    raise TypeError(

TypeError: `generator` yielded an element of shape (0,) where an element of shape (2048, 2048) was expected.


	 [[{{node PyFunc}}]] [Op:IteratorGetNext]
```

</details>

I think this shows that the generator is trying to process the "dummy" binary mask I created for some reason? It is in the same folder as the training images and referenced in the training.json like this:

```
"img_id": 57,
        "image_file": "1413.tif",
        "mask_file": "dummy",
        "locations": [
```

Is this wrong?

**Comment by jiyuuchc** [comment]
### Regarding poor model metrics

Your training losses appear reasonable. Particularly, lpn_loss = 0.0051 should produce at least ok location detections. Yet, you have very low loi_ap (evaluation of location detection).  I suspect mistakes in the validation dataset pipeline. Could you

  - Sample data from your validation dataset and visually confirm their validity?
  - Perform inference on your training images and visualize the result?

Example code for performing inference on training images:

```
import lacss.deploy

checkpoint_path = ...
train_gen = ... # same as training setup

predictor = lacss.deploy.Predictor(checkpoint_path)

image = next(train_gen)['image']
image = image[0] # remove batch dimension
label = predictor.predict_label(image)
```

### Regarding crash due to datapipelin

Because the training went through >10000 samples before the error occurs, I suspect I/O issues (esp. racing) is the culprit. I noticed that you are using the same dummy images for all samples. This might caused problem when multiple tf.data threads are trying to read the data. Suggestions:

  - Use separate "dummy" images for each input image.
  or
  - Upgrade lacss to the most recent version and remove "mask_file" from your json file.

**Comment by pakiessling** [comment]
Thank you, I was unaware of the new lacss version :)

Great Idea about double-checking the validation data:

![grafik](https://github.com/jiyuuchc/lacss/assets/104848590/a188a4a9-f51c-480f-a85a-d4483fa48345)
![grafik](https://github.com/jiyuuchc/lacss/assets/104848590/682760c8-5bfd-4da9-b813-3dadf45ed37a)

Something seems to go wrong with the calculation of the bounding boxes.

This is the code I am using:
```
def val_parser(data):
    data["image"] = tf.image.per_image_standardization(data["image"])
    data = lacss.data.resize(data, target_size=[512,512]) # resize image to match pixel size

    # It is important to pad the locations tensor so that all elements of the dataset are of the same shape
    locations = data['centroids']
    n_pad = 768 - len(locations)
    locations = tf.pad(locations, [[0, n_pad], [0,0]], constant_values=-1)

    return dict(image=tf.ensure_shape(data['image'], [512,512,2])),dict(gt_locations=data["centroids"],gt_bboxes=data["bboxes"])


val =  (
    lacss.data.dataset_from_img_mask_pairs(val_images,val_gt, image_shape=[2048, 2048, 2],)
    .map(val_parser)
    .prefetch(10)
)

# Convert the td.dataset to generator
val_gen = lacss.train.TFDatasetAdapter(val, steps=-1).get_dataset()

# make sure the dataset has the correct element structure
print(val.element_spec)
```

The ground truth files are just  2048x2048 16-bit Grayscale Tifs with 0 for background pixels and (1...n) for foreground.

**Comment by pakiessling** [comment]
Thank you I was not aware of the new lacss version.
I will try a new training run and iterference.

I checked the valdata set. The bounding boxes tend to overlap, is this a problem?
![grafik](https://github.com/jiyuuchc/lacss/assets/104848590/16b6b38c-c4d6-4f8e-ac75-49db70a7b65c)

I also noticed that I always got the same validation image back fromt the generator or am I missunderstanding how the generator works?
```
def val_parser(data):
    data["image"] = tf.image.per_image_standardization(data["image"])
    data = lacss.data.resize(data, target_size=[512,512]) # resize image to match pixel size

    # It is important to pad the locations tensor so that all elements of the dataset are of the same shape
    locations = data['centroids']
    n_pad = 768 - len(locations)
    locations = tf.pad(locations, [[0, n_pad], [0,0]], constant_values=-1)

    return dict(image=tf.ensure_shape(data['image'], [512,512,2])),dict(gt_locations=data["centroids"],gt_bboxes=data["bboxes"])


val =  (
    lacss.data.dataset_from_img_mask_pairs(val_images,val_gt, image_shape=[2048, 2048, 2],)
    .map(val_parser)
    .prefetch(10)
)

# Convert the td.dataset to generator
val_gen = lacss.train.TFDatasetAdapter(val, steps=-1).get_dataset()

# make sure the dataset has the correct element structure
print(val.element_spec)

valdata = next(iter(val))
valdata2 = next(iter(val))
valdata3 = next(iter(val))

np.array_equal(valdata[0]["image"], valdata3[0]["image"] )
> True
```

**Comment by jiyuuchc** [comment]
To iterate over tf dataset:

```
it = iter(val)
valdata_1 = next(it)
valdata_2 = next(it)
valdata_3 = next(it)
```

Your validation data appear to be be ok to me. 

Without access to your current code, I am not sure why your validation metrics were so poor. I might be able to help you more if you can share your latest checkpoint, as well as a few training and/or testing images.

**Comment by pakiessling** [comment]
I highly appreciate your help. I will upload some data shortly.

Might it be that that the low `loi_ap` is caused by difference between training and validation data? The validation data is annotated quite thoroughly, with some annotated cells not containing nuclei, while the training annotation is a quick and dirty `skimage.feature.blob_log` that might miss some nuclei (especially at the edges for some reason) and obviously every marked cell has a nuclei.

**Comment by jiyuuchc** [comment]
Unlikely. We routinely train models with "inaccurate" labels and still obtain reasonable accuracy (orders better than your results).

**Comment by pakiessling** [comment]
I have uploaded sample training and validation images as well as a checkpoint and the code I was using.
https://rwth-aachen.sciebo.de/s/FZoudLttRpWOhHm

 Thank you so much for taking the time!

**Comment by jiyuuchc** [comment]
I think I understand the problem now. It turns out that your are right -- the automatically generated point label is the issue. 

There are two difficulties regarding your data making DAPI-derived point label unsuitable for training

  - DAPI signal is very off-center and does not approximate the cell centroid
  - A significant portion of cells has no DAPI signal and thus is missing a point label

There are two potential solutions:

  1. Create point label manually.
  2. Create point label using label propagation, ie using existing model to predict point labels. I've attached a rough notebook below based on our internal test code to show you how it can work on your data.

https://colab.research.google.com/drive/1HLCn4UiKKYsFWKK0Chm3TBOZaE8td_p6?usp=drive_link

Note that the second method generally only works under semi-supervised setting -- you need to combine both labeled and unlabeled data to train. This is also very experimental -- our own testing of this method is limited (only on some nucleus segmentation problems).

**Comment by pakiessling** [comment]
Thanks a lot Ji. This is what I feared.

I think the label propagation is a little bit too complex for me.

As far as manually labeled images go, do you think good performance is possible when providing enough manually created centroids?
If you had to guess, roughly how many images would I need 100, 10.000, 100.000?
(Difficult question I know)

**Comment by jiyuuchc** [comment]
The question regarding number of images is indeed difficult to answer. Our published results were obtained using as few as 500 training images. On the other hand your images do seems to be more difficult to segment, so maybe need more training data.

Also I want to mention that testing "label propagation" method may not be as difficult as you think -- the attached notebook is adapted and already runs on your data -- I've tested it using the few images your uploaded. You just need to populate the data directory with more images to do full training. The things I am not confident about is how good will the result be.

Regardless of which approach you take, incorporating your fully-labeled data into your training (i.e., semi-supervised training) will be very helpful. Note that Lacss is designed with this in mind and accept mixed input stream (fully-labeled data + weakly-labeled data).

**Comment by pakiessling** [comment]
Cool I will give it a try.

```
ds_train = (
  ds
  .repeat()
  .map(train_parser)
  .bucket_by_sequence_length(
      element_length_func=lambda x, _: tf.shape(x["gt_locations"])[0],
      bucket_boundaries=bucket_boundaries,
      bucket_batch_sizes=bucket_batch_sizes,
      padding_values=-1.0,
      pad_to_bucket_boundary=True,
  )
  .unbatch()
  .prefetch(3)
)

```

This is throwing a
```
TypeError: Invalid `padding_values`. `padding_values` values type <dtype: 'int32'> does not match type <dtype: 'float32'> of the corresponding input component.

```
at me. Any idea what is going wrong? I also tried with -1, but same result

**Comment by jiyuuchc** [comment]
Did you change the code? The "padding_values" arg should be "-1.0" (float) instead of "-1" (int).

Ji

________________________________

**Comment by pakiessling** [comment]
I managed to fix this error by converting gt_masks returned by `train_parser `to `float`.
I also had to remove `generate_masks=True` from `lacss.data.dataset_from_img_mask_pairs`, as the argument does not seem to exist.
But now I am getting `No loss functions provided` during `logs = next(train_iter)` for the training.

https://github.com/pakiessling/lacss-test/blob/main/semi_supervised.py

**Comment by jiyuuchc** [comment]
The notebook I shared requires some experimental features in the "mt-training" branch of the Lacss. Look at the top of the notebook you will see this line:

!pip install ***@***.***_training

I think you've cloned the wrong branch based on your feedback.

Once this is corrected, I don't think you need to make any changes (except overriding various data_dir variables) -- I just rerun the notebook on Colab without running into any error.

________________________________________
