### ISSUE TITLE
train_with_point_label.ipynb error

### ISSUE THREAD

**Issue by ajiwatson** [jiyuuchc/lacss#7]
When running the Setting Up the Environment section in `train_with_point_label.ipynb`, I get an error regarding this line of code: 
`from lacss.deploy import load_from_pretrained`

I tried `from lacss.utils import load_from_pretrained` after looking through the code for `load_from_pretrained` and this seems to solve the issue.

**Comment by jiyuuchc** [comment]
Thanks for reporting the bug! Will patch.

Ji

________________________________________
From: drarcher ***@***.***>
Sent: Monday, December 4, 2023 12:04 PM
To: jiyuuchc/lacss
Cc: Subscribed
Subject: [jiyuuchc/lacss] train_with_point_label.ipynb error (Issue #7)

*** Attention: This is an external email. Use caution responding, opening attachments or clicking on links. ***

When running the Setting Up the Environment section in train_with_point_label.ipynb, I get an error regarding this line of code:
from lacss.deploy import load_from_pretrained

I tried from lacss.utils import load_from_pretrained after looking through the code for load_from_pretrained and this seems to solve the issue.

**Comment by jiyuuchc** [comment]
Fixed with commit [b27da0](https://github.com/jiyuuchc/lacss/commit/b27da0eb293a846ad655201879fd255d5817cbe1).
