### ISSUE TITLE
AttributeError: 'Predictor' object has no attribute 'predict_label'(inference.ipynb run in google clab)

### ISSUE THREAD

**Issue by Slesinger1202** [jiyuuchc/lacss#8]
![image](https://github.com/jiyuuchc/lacss/assets/148455646/6b25646e-f6a3-49d9-b97a-cfb9e607eb29)
/usr/local/lib/python3.10/dist-packages/imageio/plugins/pillow.py:304: UserWarning: Loading 16-bit (uint16) PNG as int32 due to limitations in pillow's PNG decoder. This will be fixed in a future version of pillow which will make this warning dissapear.
  warnings.warn(
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-5-c160adfeccab>](https://localhost:8080/#) in <cell line: 4>()
      2 gt = imageio.imread("image_data/test/000_masks.png")
      3 
----> 4 pred = predictor.predict_label(image.astype("float32"))
      5 
      6 # the default model outputs are JAX arrays. It is more convenient

AttributeError: 'Predictor' object has no attribute 'predict_label'

**Comment by jiyuuchc** [comment]
Fixed with commit [0796bb](https://github.com/jiyuuchc/lacss/commit/0796bbcbd6e3aed776900ae616ea976c0eebacbb)
